name: "Release Mastermind"
description: "Incorperates all our management tools within one simple action, which can be used in all your workflows to manage all your common tasks."
author: "Videndum"
branding:
  icon: "at-sign"
  color: "purple"
inputs:
  GITHUB_TOKEN:
    description: "The GITHUB_TOKEN secret"
    required: true
  config:
    description: "Config file path"
    default: ".github/config.json"
    required: false
  configJSON:
    description: "JSON string with configuration data"
    default: ""
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
