on:
  issues:
  pull_request:
  project_card:

jobs:
  release_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test release mastermind
        id: release
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
